### ISSUE TITLE
[FEAT] (BE) 필터기능 추가

### ISSUE THREAD

**Issue by Minzino** [PhilSoGooood/issue-tracker#10]
## 💡 issue
[FEAT] 필터기능 추가

## 📝 todo
- [x] 열린 이슈
- [x] 내가 작성한 이슈
- [x] 나에게 할당된 이슈
- [x] 내가 댓글을 남긴 이슈
- [x]  닫힌 이슈
